// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXDhyDD_Mh82Pfgl42VKnLLMNE3fV2Kuo',
    appId: '1:779178387053:web:bad833a50fc12108740164',
    messagingSenderId: '779178387053',
    projectId: 'hrms-1b0f5',
    authDomain: 'hrms-1b0f5.firebaseapp.com',
    storageBucket: 'hrms-1b0f5.appspot.com',
    measurementId: 'G-S99C9J74J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzBLqmxOdreI_Fsd_3AlrgDNhkOFioJFs',
    appId: '1:779178387053:android:89b316d8f3386936740164',
    messagingSenderId: '779178387053',
    projectId: 'hrms-1b0f5',
    storageBucket: 'hrms-1b0f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArixFkr2TGHQzi0noGnwI7U8OWaM3yM-M',
    appId: '1:779178387053:ios:b5e839f9e2a2d20d740164',
    messagingSenderId: '779178387053',
    projectId: 'hrms-1b0f5',
    storageBucket: 'hrms-1b0f5.appspot.com',
    iosClientId: '779178387053-7srms32bcrjqd89gg0bho17jbu4aob6l.apps.googleusercontent.com',
    iosBundleId: 'com.flexben.hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArixFkr2TGHQzi0noGnwI7U8OWaM3yM-M',
    appId: '1:779178387053:ios:fa36555ee7ce3292740164',
    messagingSenderId: '779178387053',
    projectId: 'hrms-1b0f5',
    storageBucket: 'hrms-1b0f5.appspot.com',
    iosClientId: '779178387053-tsa1thiun2h56d9lg0ngahaohk1s2vlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrAttendant.RunnerTests',
  );
}
